// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeerLearn.Infrastructure.Persistence;

#nullable disable

namespace PeerLearn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PeerLearnDbContext))]
    [Migration("20260817004006_RetireAchievementBadges")]
    partial class RetireAchievementBadges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PeerLearn.Domain.Catalog.EducationCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("EducationCategories", "catalog");
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Subjects", "catalog");
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ParentTopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentTopicId");

                    b.HasIndex("SubjectId", "Name")
                        .IsUnique();

                    b.ToTable("Topics", "catalog");
                });

            modelBuilder.Entity("PeerLearn.Domain.Communication.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessageAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("Conversations", "comms");
                });

            modelBuilder.Entity("PeerLearn.Domain.Communication.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ConversationId", "CreatedAtUtc");

                    b.HasIndex("ConversationId", "SenderUserId")
                        .HasFilter("\"ReadAtUtc\" IS NULL AND \"IsDeleted\" = FALSE");

                    b.ToTable("Messages", "comms");
                });

            modelBuilder.Entity("PeerLearn.Domain.Community.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Badges", "community");
                });

            modelBuilder.Entity("PeerLearn.Domain.Community.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EarnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.HasIndex("UserId", "EarnedAtUtc");

                    b.ToTable("UserBadges", "community");
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("WalletId", "Status");

                    b.ToTable("CreditHolds", "economy", t =>
                        {
                            t.HasCheckConstraint("CK_CreditHolds_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EarnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitialAmount")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SourceSessionId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasFilter("\"RemainingAmount\" > 0");

                    b.HasIndex("SourceSessionId")
                        .IsUnique()
                        .HasFilter("\"Source\" = 'LessonEarning'");

                    b.HasIndex("WalletId", "ExpiresAtUtc")
                        .HasFilter("\"RemainingAmount\" > 0");

                    b.HasIndex(new[] { "WalletId" }, "IX_CreditLots_WalletId");

                    b.HasIndex(new[] { "WalletId" }, "UX_CreditLots_OneWelcomeBonusPerWallet")
                        .IsUnique()
                        .HasFilter("\"Source\" = 'WelcomeBonus'");

                    b.ToTable("CreditLots", "economy", t =>
                        {
                            t.HasCheckConstraint("CK_CreditLots_InitialAmount", "\"InitialAmount\" > 0");

                            t.HasCheckConstraint("CK_CreditLots_RemainingAmount", "\"RemainingAmount\" >= 0 AND \"RemainingAmount\" <= \"InitialAmount\"");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditLotConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreditHoldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreditLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreditTransactionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreditLotId");

                    b.HasIndex("CreditTransactionId", "CreditLotId")
                        .IsUnique()
                        .HasFilter("\"CreditTransactionId\" IS NOT NULL");

                    b.HasIndex("CreditHoldId", "CreditLotId", "IsReversal")
                        .IsUnique()
                        .HasFilter("\"CreditHoldId\" IS NOT NULL");

                    b.ToTable("CreditLotConsumptions", "economy", t =>
                        {
                            t.HasCheckConstraint("CK_CreditLotConsumptions_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_CreditLotConsumptions_ReversalRequiresHold", "NOT \"IsReversal\" OR \"CreditHoldId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_CreditLotConsumptions_SingleParent", "num_nonnulls(\"CreditHoldId\", \"CreditTransactionId\") = 1");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CounterpartyUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("RelatedSessionId", "Type")
                        .IsUnique()
                        .HasFilter("\"Type\" IN ('LessonSpending', 'LessonEarning')");

                    b.HasIndex("WalletId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("CreditTransactions", "economy", t =>
                        {
                            t.HasCheckConstraint("CK_CreditTransactions_Amount", "\"Amount\" <> 0");

                            t.HasCheckConstraint("CK_CreditTransactions_TransferLegs", "\"Type\" NOT IN ('LessonEarning', 'LessonSpending') OR (\"CounterpartyUserId\" IS NOT NULL AND \"RelatedSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LockedBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets", "economy", t =>
                        {
                            t.HasCheckConstraint("CK_Wallets_AvailableBalance", "\"AvailableBalance\" >= 0");

                            t.HasCheckConstraint("CK_Wallets_LockedBalance", "\"LockedBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.TeacherCandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeclaredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("GradeYear")
                        .HasColumnType("integer");

                    b.Property<bool>("HasPedagogicalCertificate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByAdminId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeclaredAtUtc")
                        .HasFilter("\"VerifiedAtUtc\" IS NULL AND \"RejectedAtUtc\" IS NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeacherCandidateProfiles", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherCandidate_GradeYear", "\"GradeYear\" IS NULL OR \"GradeYear\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_TeacherCandidate_ReviewState", "\"VerifiedAtUtc\" IS NULL OR \"RejectedAtUtc\" IS NULL");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PhoneVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SuspendedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaughtMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("TaughtSessionCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEarnedCredits")
                        .HasColumnType("integer");

                    b.Property<string>("University")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("WelcomeCreditGrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.HasIndex("Role")
                        .HasFilter("\"Role\" <> 'Student'");

                    b.ToTable("Users", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_Users_AverageRating", "\"AverageRating\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_Users_RatingCount", "\"RatingCount\" >= 0");

                            t.HasCheckConstraint("CK_Users_TotalEarnedCredits", "\"TotalEarnedCredits\" >= 0");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HwidHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HwidHash");

                    b.HasIndex("UserId", "HwidHash")
                        .IsUnique();

                    b.ToTable("UserDevices", "identity");
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalyticsConsent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConsentIpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ConsentUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentVersion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FunctionalConsent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OnboardingCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OnboardingLastStep")
                        .HasColumnType("integer");

                    b.Property<bool>("OnboardingSuppressed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_UserPreferences_ConsentTimestamped", "(\"AnalyticsConsent\" = 'NotAsked' AND \"FunctionalConsent\" = 'NotAsked') OR (\"ConsentUpdatedAtUtc\" IS NOT NULL AND \"ConsentVersion\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_UserPreferences_OnboardingStep", "\"OnboardingLastStep\" >= 0");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Matchmaking.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfferedTopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedTopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResponderUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Matches_PendingAge")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("OfferedTopicId");

                    b.HasIndex("RequestedTopicId");

                    b.HasIndex("InitiatorUserId", "Status");

                    b.HasIndex("ResponderUserId", "Status");

                    b.HasIndex("InitiatorUserId", "ResponderUserId", "RequestedTopicId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("Matches", "matchmaking", t =>
                        {
                            t.HasCheckConstraint("CK_Matches_DifferentUsers", "\"InitiatorUserId\" <> \"ResponderUserId\"");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Matchmaking.PortfolioEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVolunteer")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SelfAssessedLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Direction")
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("UserId", "TopicId", "Direction")
                        .IsUnique();

                    b.ToTable("PortfolioEntries", "matchmaking", t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioEntries_Level", "\"SelfAssessedLevel\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Moderation.AdminActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending();

                    b.HasIndex("ActorUserId", "CreatedAtUtc");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AdminActionLogs", "moderation");
                });

            modelBuilder.Entity("PeerLearn.Domain.Moderation.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RaisedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TutorStatement")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("TutorStatementAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RaisedByUserId");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Open', 'UnderReview')");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("Disputes", "moderation");
                });

            modelBuilder.Entity("PeerLearn.Domain.Moderation.HwidBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BannedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HwidHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RelatedUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HwidHash")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.ToTable("HwidBans", "moderation");
                });

            modelBuilder.Entity("PeerLearn.Domain.Moderation.UserSanction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IssuedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("UserSanctions", "moderation");
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.LessonSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletionRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreditCost")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVolunteer")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TopicId");

                    b.HasIndex("VerificationCode")
                        .IsUnique();

                    b.HasIndex("Status", "ScheduledEndUtc");

                    b.HasIndex("StudentUserId", "ScheduledStartUtc");

                    b.HasIndex("TutorUserId", "ScheduledStartUtc");

                    b.ToTable("LessonSessions", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_LessonSessions_CreditCost", "\"CreditCost\" >= 0");

                            t.HasCheckConstraint("CK_LessonSessions_DifferentUsers", "\"TutorUserId\" <> \"StudentUserId\"");

                            t.HasCheckConstraint("CK_LessonSessions_Duration", "\"DurationMinutes\" IN (30, 60)");

                            t.HasCheckConstraint("CK_LessonSessions_EndAfterStart", "\"ScheduledEndUtc\" > \"ScheduledStartUtc\"");

                            t.HasCheckConstraint("CK_LessonSessions_VolunteerNoReward", "NOT \"IsVolunteer\" OR \"CreditCost\" = 0");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SessionProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ContentDeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDuplicateHash")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_SessionProofs_Retention")
                        .HasFilter("\"ContentDeletedAtUtc\" IS NULL");

                    b.HasIndex("SessionId");

                    b.HasIndex("Sha256Hash");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("SessionProofs", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_SessionProofs_FileSize", "\"FileSizeBytes\" > 0 AND \"FileSizeBytes\" <= 10485760");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SessionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PunctualityScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeachingScore")
                        .HasColumnType("integer");

                    b.Property<bool>("WasVolunteerSession")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("RevieweeUserId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("SessionId", "ReviewerUserId")
                        .IsUnique();

                    b.ToTable("SessionReviews", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_SessionReviews_NotSelf", "\"ReviewerUserId\" <> \"RevieweeUserId\"");

                            t.HasCheckConstraint("CK_SessionReviews_PunctualityScore", "\"PunctualityScore\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SessionReviews_Score", "\"Score\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SessionReviews_TeachingScore", "\"TeachingScore\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SessionReviewTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId", "Tag")
                        .IsUnique();

                    b.ToTable("SessionReviewTags", "scheduling");
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SweepFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastFailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc");

                    b.HasIndex("RecordType", "RecordId")
                        .IsUnique();

                    b.ToTable("SweepFailures", "scheduling", t =>
                        {
                            t.HasCheckConstraint("CK_SweepFailures_Count", "\"FailureCount\" > 0");
                        });
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.EducationCategory", b =>
                {
                    b.HasOne("PeerLearn.Domain.Catalog.EducationCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.Subject", b =>
                {
                    b.HasOne("PeerLearn.Domain.Catalog.EducationCategory", "Category")
                        .WithMany("Subjects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.Topic", b =>
                {
                    b.HasOne("PeerLearn.Domain.Catalog.Topic", "ParentTopic")
                        .WithMany("SubTopics")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeerLearn.Domain.Catalog.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentTopic");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PeerLearn.Domain.Communication.Conversation", b =>
                {
                    b.HasOne("PeerLearn.Domain.Matchmaking.Match", null)
                        .WithOne()
                        .HasForeignKey("PeerLearn.Domain.Communication.Conversation", "MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Communication.Message", b =>
                {
                    b.HasOne("PeerLearn.Domain.Communication.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PeerLearn.Domain.Community.UserBadge", b =>
                {
                    b.HasOne("PeerLearn.Domain.Community.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditHold", b =>
                {
                    b.HasOne("PeerLearn.Domain.Scheduling.LessonSession", null)
                        .WithOne()
                        .HasForeignKey("PeerLearn.Domain.Economy.CreditHold", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Economy.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditLot", b =>
                {
                    b.HasOne("PeerLearn.Domain.Scheduling.LessonSession", null)
                        .WithMany()
                        .HasForeignKey("SourceSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeerLearn.Domain.Economy.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditLotConsumption", b =>
                {
                    b.HasOne("PeerLearn.Domain.Economy.CreditHold", null)
                        .WithMany()
                        .HasForeignKey("CreditHoldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeerLearn.Domain.Economy.CreditLot", null)
                        .WithMany()
                        .HasForeignKey("CreditLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Economy.CreditTransaction", null)
                        .WithMany()
                        .HasForeignKey("CreditTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.CreditTransaction", b =>
                {
                    b.HasOne("PeerLearn.Domain.Scheduling.LessonSession", null)
                        .WithMany()
                        .HasForeignKey("RelatedSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeerLearn.Domain.Economy.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Economy.Wallet", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("PeerLearn.Domain.Economy.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.TeacherCandidateProfile", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.UserDevice", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.UserPreference", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Matchmaking.Match", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Catalog.Topic", null)
                        .WithMany()
                        .HasForeignKey("OfferedTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeerLearn.Domain.Catalog.Topic", null)
                        .WithMany()
                        .HasForeignKey("RequestedTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ResponderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Matchmaking.PortfolioEntry", b =>
                {
                    b.HasOne("PeerLearn.Domain.Catalog.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Moderation.AdminActionLog", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Moderation.Dispute", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Scheduling.LessonSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Moderation.UserSanction", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.LessonSession", b =>
                {
                    b.HasOne("PeerLearn.Domain.Matchmaking.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Catalog.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("TutorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SessionProof", b =>
                {
                    b.HasOne("PeerLearn.Domain.Scheduling.LessonSession", null)
                        .WithMany("Proofs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SessionReview", b =>
                {
                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RevieweeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerLearn.Domain.Scheduling.LessonSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SessionReviewTag", b =>
                {
                    b.HasOne("PeerLearn.Domain.Scheduling.SessionReview", "Review")
                        .WithMany("Tags")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.EducationCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.Subject", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("PeerLearn.Domain.Catalog.Topic", b =>
                {
                    b.Navigation("SubTopics");
                });

            modelBuilder.Entity("PeerLearn.Domain.Communication.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PeerLearn.Domain.Identity.User", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.LessonSession", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("PeerLearn.Domain.Scheduling.SessionReview", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
