using PeerLearn.Domain.Catalog;

namespace PeerLearn.Infrastructure.Persistence;

/// <summary>
/// YKS müfredatı — TYT ve AYT, sekiz ders, 767 konu. Kataloğun TANIMI budur.
///
/// NEDEN KOD İÇİNDE (harici JSON/veritabanı içeriği olarak değil): bu bir kullanıcı verisi
/// değil, ürünün ders kataloğunun tanımı. Kodda durunca sürüm kontrolüne girer, kod
/// incelemesinden geçer ve <see cref="DbSeeder"/> ile aynı dağıtımda güncellenir. Harici
/// dosya olsaydı şemayla içeriğin sürümü ayrışabilirdi.
///
/// AYT "Türkçe", ÖSYM'de Türk Dili ve Edebiyatı testidir; branş adı ürün genelinde tutarlı
/// kalsın diye Türkçe olarak tutuluyor, konular edebiyat müfredatından geliyor.
///
/// LİSTE EKSİKSİZDİR — kısaltma, "vb." veya atlama yoktur. Konu çıkarırken DbSeeder'ın
/// EŞİTLEYİCİ olduğunu unutma: listeden düşen konu SİLİNMEZ, IsActive=false yapılır
/// (mevcut ders kayıtları ona FK ile bağlı olabilir ve FK'lar Restrict'tir).
/// </summary>
public static class Curriculum
{
    /// <summary>Bir branşın tek bir sınav seviyesindeki (TYT/AYT) konu listesi.</summary>
    public sealed record BranchTopics(SubjectBranch Branch, string[] Topics);

    public static readonly BranchTopics[] TYT =
    [
        new(SubjectBranch.Turkce,
        [
            "Sözcükte Anlam",
            "Deyimler ve Atasözleri",
            "Söz Öbeklerinde Anlam",
            "Cümlede Anlam",
            "Cümle Yorumlama",
            "Paragrafta Anlam",
            "Paragrafta Konu ve Ana Düşünce",
            "Paragrafta Yardımcı Düşünce",
            "Paragrafta Yapı",
            "Paragrafta Anlatım Biçimleri",
            "Düşünceyi Geliştirme Yolları",
            "Anlatım Türleri",
            "Sözel Mantık ve Muhakeme",
            "Ses Bilgisi",
            "Ses Olayları",
            "Yazım Kuralları",
            "Noktalama İşaretleri",
            "Sözcükte Yapı (Kök ve Ekler)",
            "Yapım Ekleri ve Çekim Ekleri",
            "Sözcük Türleri",
            "İsim (Ad)",
            "İsim Tamlamaları",
            "Sıfat (Ön Ad)",
            "Sıfat Tamlamaları",
            "Zamir (Adıl)",
            "Zarf (Belirteç)",
            "Edat (İlgeç)",
            "Bağlaç",
            "Ünlem",
            "Fiiller (Eylemler)",
            "Fiilde Kip ve Kişi",
            "Fiilde Zaman (Anlam) Kayması",
            "Ek Fiil",
            "Fiilde Yapı",
            "Fiilimsiler (Eylemsiler)",
            "Fiilde Çatı",
            "Cümlenin Ögeleri",
            "Cümle Türleri",
            "Anlatım Bozuklukları",
            "Sözcük Grupları",
        ]), // Türkçe: 40 konu

        new(SubjectBranch.Tarih,
        [
            "Tarih Bilimine Giriş ve Tarih Yazıcılığı",
            "Tarih ve Zaman",
            "Zaman ve Takvim",
            "İnsanlığın İlk Dönemleri",
            "İlk Yerleşmeler ve İlk Uygarlıklar",
            "Anadolu'da Kurulan İlk Uygarlıklar",
            "Orta Çağ'da Dünya",
            "Orta Çağ'da Siyasi Yapılar ve Feodalizm",
            "İlk ve Orta Çağlarda Türk Dünyası",
            "İlk Türk Devletleri (Asya Hun, Göktürk, Uygur)",
            "Kavimler Göçü",
            "İslam Medeniyetinin Doğuşu",
            "Türklerin İslamiyet'i Kabulü ve İlk Türk İslam Devletleri",
            "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
            "Beylikten Devlete Osmanlı Siyaseti",
            "Devletleşme Sürecinde Savaşçılar ve Askerler",
            "Beylikten Devlete Osmanlı Medeniyeti",
            "Dünya Gücü Osmanlı",
            "Sultan ve Osmanlı Merkez Teşkilatı",
            "Klasik Çağda Osmanlı Toplum Düzeni",
            "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
            "Değişim Çağında Avrupa ve Osmanlı",
            "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
            "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
            "Sermaye ve Emek",
            "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
            "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
            "I. Dünya Savaşı",
            "Mondros Ateşkes Antlaşması ve İşgaller",
            "Milli Mücadele",
            "Kurtuluş Savaşı Cepheleri ve Antlaşmaları",
            "Atatürkçülük ve Türk İnkılabı",
            "Atatürk İlke ve İnkılapları",
            "Atatürk Dönemi Türk Dış Politikası",
        ]), // Tarih: 34 konu

        new(SubjectBranch.Cografya,
        [
            "Doğa ve İnsan Etkileşimi",
            "Dünya'nın Şekli ve Hareketleri",
            "Coğrafi Konum (Matematik Konum ve Özel Konum)",
            "Paraleller ve Meridyenler",
            "Yerel Saat ve Saat Dilimleri",
            "Harita Bilgisi",
            "Ölçek ve Harita Türleri",
            "Yer Şekillerinin Haritalarda Gösterilmesi (İzohips)",
            "Atmosfer ve Özellikleri",
            "Sıcaklık ve Sıcaklığın Dağılışı",
            "Basınç ve Rüzgârlar",
            "Nem, Yağış ve Buharlaşma",
            "İklim Elemanları",
            "İklim Tipleri ve Dünya İklimleri",
            "Türkiye'nin İklimi",
            "Dünya'nın İç Yapısı",
            "Levha Tektoniği",
            "Kayaçlar",
            "İç Kuvvetler (Orojenez, Epirojenez, Volkanizma, Deprem)",
            "Dış Kuvvetler (Akarsu, Rüzgâr, Buzul, Dalga ve Karstik Şekiller)",
            "Türkiye'nin Yer Şekilleri",
            "Su Kaynakları (Okyanuslar, Denizler, Göller, Akarsular, Yer Altı Suları)",
            "Toprak ve Toprak Türleri",
            "Bitki Örtüsü ve Doğal Bitki Toplulukları",
            "Nüfus ve Nüfusun Özellikleri",
            "Nüfus Piramitleri ve Nüfus Sayımları",
            "Göç ve Göçün Nedenleri",
            "Yerleşme ve Yerleşme Türleri",
            "Şehirleşme",
            "Ekonomik Faaliyet Türleri",
            "Tarım ve Hayvancılık",
            "Madenler ve Enerji Kaynakları",
            "Sanayi",
            "Ulaşım ve Uluslararası Ulaşım Hatları",
            "Ticaret",
            "Turizm",
            "Bölge Kavramı ve Bölge Türleri",
            "Doğal Afetler",
            "Çevre ve Toplum",
            "Çevre Sorunları",
            "Doğal Kaynakların Sürdürülebilir Kullanımı",
        ]), // Coğrafya: 41 konu

        new(SubjectBranch.Matematik,
        [
            "Temel Kavramlar",
            "Sayı Kümeleri",
            "Sayı Basamakları",
            "Bölme ve Bölünebilme Kuralları",
            "Asal Çarpanlara Ayırma",
            "EBOB ve EKOK",
            "Rasyonel Sayılar",
            "Ondalık Sayılar",
            "Basit Eşitsizlikler",
            "Mutlak Değer",
            "Üslü Sayılar",
            "Köklü Sayılar",
            "Çarpanlara Ayırma",
            "Özdeşlikler",
            "Oran ve Orantı",
            "Doğru Orantı ve Ters Orantı",
            "Birinci Dereceden Denklemler",
            "Denklem Çözme",
            "Sayı Problemleri",
            "Kesir Problemleri",
            "Yaş Problemleri",
            "Hareket ve Hız Problemleri",
            "İşçi ve Havuz Problemleri",
            "Yüzde Problemleri",
            "Kâr-Zarar Problemleri",
            "Karışım Problemleri",
            "Grafik Problemleri",
            "Rutin Olmayan Problemler",
            "Kümeler",
            "Kartezyen Çarpım",
            "Mantık",
            "Fonksiyonlar",
            "İşlem ve Modüler Aritmetik",
            "Polinomlar",
            "İkinci Dereceden Denklemler",
            "Eşitsizlikler ve Eşitsizlik Sistemleri",
            "Permütasyon",
            "Kombinasyon",
            "Binom Açılımı",
            "Olasılık",
            "Veri Analizi ve İstatistik",
            "Sayı Dizileri ve Örüntüler",
        ]), // Matematik: 42 konu

        new(SubjectBranch.Geometri,
        [
            "Geometrik Kavramlar (Nokta, Doğru, Düzlem)",
            "Doğruda Açılar",
            "Üçgende Açılar",
            "Üçgende Açı-Kenar Bağıntıları",
            "Dik Üçgen ve Pisagor Bağıntısı",
            "Özel Dik Üçgenler",
            "Öklid Bağıntıları",
            "İkizkenar Üçgen",
            "Eşkenar Üçgen",
            "Üçgende Açıortay Bağıntıları",
            "Üçgende Kenarortay Bağıntıları",
            "Üçgende Yardımcı Elemanlar",
            "Üçgende Eşlik",
            "Üçgende Benzerlik",
            "Thales Teoremi",
            "Üçgende Alan",
            "Çokgenler",
            "Dörtgenler",
            "Deltoid",
            "Paralelkenar",
            "Eşkenar Dörtgen",
            "Dikdörtgen",
            "Kare",
            "Yamuk",
            "Çember ve Daire",
            "Çemberde Açı",
            "Çemberde Uzunluk",
            "Çemberde Teğet ve Kirişler",
            "Dairede Çevre ve Alan",
            "Analitik Geometride Nokta",
            "Analitik Geometride Doğru",
            "Çemberin Analitik İncelenmesi",
            "Dönüşüm Geometrisi",
            "Öteleme",
            "Yansıma ve Simetri",
            "Döndürme",
            "Katı Cisimler",
            "Dikdörtgenler Prizması",
            "Küp",
            "Silindir",
            "Piramit",
            "Koni",
            "Küre",
            "Katı Cisimlerde Yüzey Alanı ve Hacim Hesapları",
        ]), // Geometri: 44 konu

        new(SubjectBranch.Fizik,
        [
            "Fizik Bilimine Giriş",
            "Fizik Biliminin Alt Alanları",
            "Fiziksel Nicelikler ve Birimler",
            "Skaler ve Vektörel Büyüklükler",
            "Madde ve Özellikleri",
            "Kütle, Hacim ve Özkütle",
            "Katılarda Dayanıklılık",
            "Adezyon ve Kohezyon",
            "Yüzey Gerilimi",
            "Kılcallık",
            "Basınç",
            "Katı Basıncı",
            "Sıvı Basıncı",
            "Gaz Basıncı ve Açık Hava Basıncı",
            "Pascal Prensibi",
            "Bernoulli İlkesi",
            "Sıvıların Kaldırma Kuvveti",
            "Gazların Kaldırma Kuvveti",
            "Isı, Sıcaklık ve İç Enerji",
            "Isı Alışverişi ve Isıl Denge",
            "Hâl Değişimi",
            "Genleşme",
            "Isı İletim Yolları",
            "Hareket (Konum, Yer Değiştirme, Sürat ve Hız)",
            "Sabit Hızlı Hareket",
            "Sabit İvmeli Hareket",
            "Hareket Grafikleri",
            "Kuvvet ve Newton'un Hareket Yasaları",
            "Sürtünme Kuvveti",
            "Kuvvet, Tork ve Denge",
            "Kütle Merkezi ve Ağırlık Merkezi",
            "Basit Makineler",
            "İş, Güç ve Enerji",
            "Enerjinin Korunumu ve Dönüşümü",
            "Verim",
            "Elektrostatik ve Elektriklenme",
            "Coulomb Kuvveti",
            "Elektrik Akımı, Potansiyel Fark ve Direnç",
            "Ohm Kanunu",
            "Elektrik Devreleri",
            "Üreteçler ve Elektrik Enerjisi",
            "Elektriksel Güç ve Enerji Hesapları",
            "Mıknatıslar ve Manyetik Alan",
            "Akımın Manyetik Etkisi",
            "Dalgalar ve Temel Dalga Bilgileri",
            "Yay Dalgaları",
            "Su Dalgaları",
            "Ses Dalgaları",
            "Deprem Dalgaları",
            "Işık ve Aydınlanma",
            "Gölge",
            "Yansıma ve Düzlem Aynalar",
            "Küresel Aynalar",
            "Işığın Kırılması",
            "Mercekler",
            "Renk ve Prizma",
            "Optik Aletler",
        ]), // Fizik: 57 konu

        new(SubjectBranch.Kimya,
        [
            "Kimya Bilimi",
            "Simyadan Kimyaya",
            "Kimyanın Uygulama Alanları ve Meslekler",
            "Kimyacıların Kullandığı Sembol ve Birimler",
            "Fiziksel ve Kimyasal Değişimler",
            "Laboratuvar Güvenliği ve Uyarı İşaretleri",
            "Atomun Yapısı",
            "Atom Modelleri",
            "Atomun Temel Tanecikleri",
            "İzotop, İyon ve İzoelektronik Kavramları",
            "Periyodik Sistem",
            "Periyodik Özellikler",
            "Elementlerin Sınıflandırılması",
            "Kimyasal Türler Arası Etkileşimler",
            "Güçlü Etkileşimler (İyonik Bağ, Kovalent Bağ, Metalik Bağ)",
            "Zayıf Etkileşimler (Van der Waals Bağları ve Hidrojen Bağı)",
            "Lewis Yapıları",
            "Bileşiklerin Formülleri ve Adlandırılması",
            "Maddenin Halleri",
            "Katılar",
            "Sıvılar",
            "Gazlar",
            "Hâl Değişimleri",
            "Plazma",
            "Kimyanın Temel Kanunları",
            "Kütlenin Korunumu Kanunu",
            "Sabit Oranlar Kanunu",
            "Katlı Oranlar Kanunu",
            "Mol Kavramı",
            "Kimyasal Hesaplamalar",
            "Kimyasal Tepkime Denklemleri ve Denkleştirme",
            "Sınırlayıcı Bileşen ve Verim Hesapları",
            "Karışımlar",
            "Homojen Karışımlar (Çözeltiler)",
            "Heterojen Karışımlar",
            "Derişim Birimleri",
            "Karışımların Ayrılma Yöntemleri",
            "Asitler ve Bazlar",
            "Asit-Baz Tepkimeleri ve Nötrleşme",
            "pH ve pOH Kavramı",
            "Tuzlar",
            "Asit Yağmurları",
            "Doğa ve Kimya",
            "Su ve Hayat",
            "Kimya Her Yerde",
            "Temizlik Maddeleri",
            "Polimerler",
            "İlaçlar ve Kozmetik Ürünler",
            "Gübreler",
            "Gıda Katkı Maddeleri",
            "Yapı Malzemeleri",
            "Kimya Endüstrisi",
        ]), // Kimya: 52 konu

        new(SubjectBranch.Biyoloji,
        [
            "Biyoloji Bilimi ve Canlıların Ortak Özellikleri",
            "Canlıların Yapısındaki Temel Bileşikler",
            "İnorganik Bileşikler (Su, Mineraller, Asitler, Bazlar ve Tuzlar)",
            "Karbonhidratlar",
            "Lipitler",
            "Proteinler",
            "Enzimler",
            "Vitaminler",
            "Hormonlar",
            "Nükleik Asitler (DNA ve RNA)",
            "ATP",
            "Hücre ve Hücre Teorisi",
            "Prokaryot ve Ökaryot Hücre",
            "Hücre Zarı ve Yapısı",
            "Hücre Duvarı",
            "Sitoplazma ve Organeller",
            "Çekirdek",
            "Hücre Zarından Madde Geçişi",
            "Pasif Taşıma (Difüzyon, Ozmoz ve Kolaylaştırılmış Difüzyon)",
            "Aktif Taşıma",
            "Endositoz ve Ekzositoz",
            "Canlıların Sınıflandırılması",
            "Bakteriler Alemi",
            "Arkeler Alemi",
            "Protista Alemi",
            "Mantarlar Alemi",
            "Bitkiler Alemi",
            "Hayvanlar Alemi",
            "Virüsler",
            "Hücre Bölünmeleri",
            "Mitoz Bölünme",
            "Eşeysiz Üreme",
            "Mayoz Bölünme",
            "Eşeyli Üreme",
            "Kalıtım ve Mendel Genetiği",
            "Çaprazlamalar ve Olasılık Hesapları",
            "Eşeye Bağlı Kalıtım",
            "Kan Grupları",
            "Soy Ağacı ve Akraba Evlilikleri",
            "Genetik Mühendisliği ve Biyoteknoloji",
            "Ekosistem Ekolojisi",
            "Madde ve Enerji Akışı",
            "Besin Zinciri ve Besin Piramidi",
            "Madde Döngüleri",
            "Güncel Çevre Sorunları",
            "Doğal Kaynakların Sürdürülebilir Kullanımı",
        ]), // Biyoloji: 46 konu

    ];

    public static readonly BranchTopics[] AYT =
    [
        new(SubjectBranch.Turkce,
        [
            "Sözcükte Anlam",
            "Cümlede Anlam",
            "Paragrafta Anlam",
            "Yazım Kuralları ve Noktalama İşaretleri",
            "Anlatım Bozuklukları",
            "Cümlenin Ögeleri ve Cümle Türleri",
            "İsim Tamlamaları ve Fiilimsiler",
            "Edebiyat Bilimine Giriş",
            "Edebiyatın Bilimlerle İlişkisi",
            "Güzel Sanatlar ve Edebiyat",
            "Metinlerin Sınıflandırılması",
            "İletişim ve Dilin İşlevleri",
            "Türkçenin Tarihî Gelişimi",
            "Türk Edebiyatının Tarihî Dönemleri",
            "Şiir Bilgisi ve Nazım Birimleri",
            "Nazım Biçimleri ve Nazım Türleri",
            "Şiirde Ahenk Unsurları (Ölçü, Kafiye, Redif, Aliterasyon, Asonans)",
            "Şiirde Tema, Konu ve İmge",
            "Söz Sanatları (Edebî Sanatlar)",
            "Edebî Akımlar",
            "İslamiyet Öncesi Türk Edebiyatı (Sözlü Dönem ve Yazılı Dönem)",
            "Destan",
            "Geçiş Dönemi Türk Edebiyatı ve Eserleri",
            "Halk Edebiyatının Genel Özellikleri",
            "Anonim Halk Edebiyatı",
            "Âşık Tarzı Halk Edebiyatı",
            "Dinî-Tasavvufi Halk Edebiyatı",
            "Divan Edebiyatının Genel Özellikleri",
            "Divan Şiiri Nazım Biçimleri",
            "Divan Edebiyatı Nesir Türleri",
            "Mesnevi",
            "Tanzimat Dönemi Edebiyatı",
            "Servetifünun (Edebiyat-ı Cedide) Edebiyatı",
            "Fecriati Edebiyatı",
            "Millî Edebiyat Dönemi",
            "Beş Hececiler",
            "Yedi Meşaleciler",
            "Cumhuriyet Dönemi Türk Edebiyatı",
            "Cumhuriyet Dönemi Türk Şiiri",
            "Saf (Öz) Şiir Anlayışı",
            "Toplumcu Gerçekçi Şiir",
            "Garip (Birinci Yeni) Akımı",
            "İkinci Yeni Şiiri",
            "Hisarcılar ve Maviciler",
            "Modern Türk Şiiri",
            "1980 Sonrası Türk Şiiri",
            "Cumhuriyet Dönemi Halk Şiiri",
            "Türkiye Dışındaki Çağdaş Türk Şiiri",
            "Hikâye (Öykü) ve Türleri",
            "Olay Hikâyesi ve Durum Hikâyesi",
            "Dede Korkut Hikâyeleri",
            "Halk Hikâyeleri",
            "Tanzimat Dönemi Hikâyesi",
            "Servetifünun Dönemi Hikâyesi",
            "Millî Edebiyat Dönemi Hikâyesi",
            "Cumhuriyet Dönemi Hikâyesi",
            "Modernist Hikâye",
            "Küçürek (Minimal) Hikâye",
            "Masal ve Fabl",
            "Roman ve Roman Türleri",
            "Dünya Edebiyatında Roman",
            "Tanzimat Dönemi Romanı",
            "Servetifünun Dönemi Romanı",
            "Millî Edebiyat Dönemi Romanı",
            "Cumhuriyet Dönemi Romanı (1923-1950)",
            "Cumhuriyet Dönemi Romanı (1950-1980)",
            "1980 Sonrası Türk Romanı",
            "Modernist ve Postmodernist Roman",
            "Türk Dünyası Edebiyatında Roman",
            "Tiyatro ve Tiyatro Türleri",
            "Geleneksel Türk Tiyatrosu",
            "Modern Türk Tiyatrosu",
            "Cumhuriyet Dönemi Türk Tiyatrosu",
            "Dünya Edebiyatında Tiyatro",
            "Makale",
            "Deneme",
            "Eleştiri",
            "Fıkra (Köşe Yazısı)",
            "Sohbet (Söyleşi)",
            "Mülakat (Görüşme)",
            "Röportaj",
            "Anı (Hatıra)",
            "Günlük",
            "Biyografi ve Otobiyografi",
            "Mektup",
            "Söylev (Hitabet)",
            "Gezi Yazısı",
            "Haber Metni",
        ]), // Türkçe: 88 konu

        new(SubjectBranch.Tarih,
        [
            "Tarih ve Zaman",
            "İnsanlığın İlk Dönemleri",
            "Orta Çağ'da Dünya",
            "İlk ve Orta Çağlarda Türk Dünyası",
            "İslam Medeniyetinin Doğuşu",
            "Türklerin İslamiyet'i Kabulü ve İlk Türk İslam Devletleri",
            "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
            "Beylikten Devlete Osmanlı Siyaseti",
            "Devletleşme Sürecinde Savaşçılar ve Askerler",
            "Beylikten Devlete Osmanlı Medeniyeti",
            "Dünya Gücü Osmanlı",
            "Sultan ve Osmanlı Merkez Teşkilatı",
            "Klasik Çağda Osmanlı Toplum Düzeni",
            "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
            "Değişim Çağında Avrupa ve Osmanlı",
            "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
            "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
            "Sermaye ve Emek",
            "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
            "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
            "I. Dünya Savaşı",
            "Mondros Ateşkes Antlaşması ve İşgaller",
            "Kuvâ-yı Milliye ve Cemiyetler",
            "Milli Mücadele",
            "Kurtuluş Savaşı Cepheleri ve Antlaşmaları",
            "Lozan Barış Antlaşması",
            "Atatürkçülük ve Türk İnkılabı",
            "Atatürk İlke ve İnkılapları",
            "Atatürk Dönemi Türk Dış Politikası",
            "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
            "II. Dünya Savaşı Sürecinde Türkiye ve Dünya",
            "II. Dünya Savaşı Sonrasında Türkiye ve Dünya",
            "Soğuk Savaş Dönemi",
            "Yumuşama Dönemi ve Sonrası",
            "Toplumsal Devrim Çağında Dünya ve Türkiye",
            "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya",
            "Küreselleşen Dünya",
            "1945 Sonrası Türk Dış Politikası",
        ]), // Tarih: 38 konu

        new(SubjectBranch.Cografya,
        [
            "Ekosistem ve Ekosistemin Unsurları",
            "Biyoçeşitlilik",
            "Biyomlar",
            "Canlıların Yeryüzüne Dağılışını Etkileyen Faktörler",
            "Enerji Akışı ve Madde Döngüleri",
            "Ekstrem Doğa Olayları",
            "Küresel İklim Değişimi",
            "Doğa ve İnsan Etkileşiminin Tarihsel Gelişimi",
            "Nüfus Politikaları",
            "Nüfus Projeksiyonları",
            "Şehirlerin Fonksiyonları ve Etki Alanları",
            "Şehirleşme, Sanayi ve Göç İlişkisi",
            "Türkiye'de Şehirleşme ve Şehirlerin Fonksiyonları",
            "Türkiye'de Kır Yerleşmeleri",
            "Yerleşmelerin Özellikleri ve Sınıflandırılması",
            "Ekonomik Faaliyet Türleri",
            "Doğal Kaynaklar ve Kullanımı",
            "Ekonomik Faaliyetlerin Sosyal ve Kültürel Etkileri",
            "Geçmişten Geleceğe Şehir, Göç ve Ekonomi",
            "Türkiye'nin Ekonomi Politikaları",
            "Türkiye Ekonomisinin Sektörel Dağılımı",
            "Türkiye'de Tarım",
            "Türkiye'de Hayvancılık",
            "Türkiye'de Ormancılık",
            "Türkiye'de Madenler ve Enerji Kaynakları",
            "Türkiye'de Sanayi",
            "Türkiye'de Ulaşım",
            "Türkiye'de Ticaret",
            "Türkiye'de Turizm",
            "Türkiye'nin İşlevsel Bölgeleri",
            "Türkiye'de Bölgesel Kalkınma Projeleri",
            "İlk Kültür Merkezleri ve İlk Medeniyetler",
            "Kültür Bölgelerinin Oluşumu",
            "Türk Kültürü ve Türk Kültür Bölgeleri",
            "Küresel Ticaret",
            "Küresel Turizm ve Turizmin Etkileri",
            "Küreselleşme",
            "Küresel ve Bölgesel Örgütler",
            "Türkiye'nin Jeopolitik Konumu",
            "Enerji Nakil Hatları ve Güzergâhları",
            "Çatışma Bölgeleri",
            "Bölgeler ve Ülkeler",
            "Gelişmiş ve Gelişmekte Olan Ülkeler",
            "Çevre Sorunları ve Türleri",
            "Küresel Çevre Sorunları",
            "Çevre Sorunlarının Çözümüne Yönelik Yaklaşımlar",
            "Doğal Kaynakların Sürdürülebilir Kullanımı",
            "Geri Dönüşüm",
            "Çevre Politikaları ve Uluslararası Çevre Örgütleri",
            "Doğal Afetler ve Afet Yönetimi",
        ]), // Coğrafya: 50 konu

        new(SubjectBranch.Matematik,
        [
            "Temel Kavramlar",
            "Sayı Basamakları",
            "Bölme ve Bölünebilme Kuralları",
            "EBOB ve EKOK",
            "Rasyonel Sayılar",
            "Basit Eşitsizlikler",
            "Mutlak Değer",
            "Üslü Sayılar",
            "Köklü Sayılar",
            "Çarpanlara Ayırma",
            "Oran ve Orantı",
            "Denklem Çözme",
            "Problemler",
            "Kümeler",
            "Kartezyen Çarpım",
            "Mantık",
            "Fonksiyonlar",
            "Bileşke Fonksiyon ve Ters Fonksiyon",
            "Polinomlar",
            "İkinci Dereceden Denklemler",
            "İkinci Dereceden Eşitsizlikler",
            "Parabol",
            "Permütasyon",
            "Kombinasyon",
            "Binom Açılımı",
            "Olasılık",
            "Koşullu Olasılık",
            "İstatistik",
            "Karmaşık Sayılar",
            "Karmaşık Sayılarda Kutupsal Gösterim ve De Moivre Formülü",
            "Trigonometri",
            "Trigonometrik Fonksiyonlar",
            "Toplam-Fark ve Yarım Açı Formülleri",
            "Trigonometrik Denklemler",
            "Ters Trigonometrik Fonksiyonlar",
            "Üstel Fonksiyon",
            "Logaritma",
            "Logaritmik Denklemler ve Eşitsizlikler",
            "Diziler",
            "Aritmetik Dizi",
            "Geometrik Dizi",
            "Toplam ve Çarpım Sembolü",
            "Limit ve Süreklilik",
            "Türev",
            "Türev Uygulamaları (Maksimum-Minimum, Grafik Çizimi, Değişim Hızı)",
            "Belirsiz İntegral",
            "Belirli İntegral",
            "İntegralin Uygulamaları (Alan ve Hacim Hesapları)",
        ]), // Matematik: 48 konu

        new(SubjectBranch.Geometri,
        [
            "Temel Geometrik Kavramlar",
            "Doğruda Açılar",
            "Üçgende Açılar",
            "Üçgende Açı-Kenar Bağıntıları",
            "Dik Üçgen ve Pisagor Bağıntısı",
            "Öklid Bağıntıları",
            "İkizkenar Üçgen",
            "Eşkenar Üçgen",
            "Üçgende Açıortay Bağıntıları",
            "Üçgende Kenarortay Bağıntıları",
            "Üçgende Eşlik",
            "Üçgende Benzerlik",
            "Thales Teoremi",
            "Menelaus ve Ceva Teoremleri",
            "Üçgende Alan",
            "Üçgende Trigonometrik Bağıntılar (Sinüs ve Kosinüs Teoremi)",
            "Çokgenler",
            "Dörtgenler",
            "Deltoid",
            "Paralelkenar",
            "Eşkenar Dörtgen",
            "Dikdörtgen",
            "Kare",
            "Yamuk",
            "Çember ve Daire",
            "Çemberde Açı",
            "Çemberde Uzunluk",
            "Çemberde Teğet ve Kirişler",
            "Çemberde Kuvvet",
            "Dairede Çevre ve Alan",
            "Noktanın Analitik İncelenmesi",
            "Doğrunun Analitik İncelenmesi",
            "Çemberin Analitik İncelenmesi",
            "Dönüşüm Geometrisi",
            "Öteleme",
            "Yansıma ve Simetri",
            "Döndürme",
            "Katı Cisimler",
            "Dikdörtgenler Prizması",
            "Küp",
            "Silindir",
            "Piramit",
            "Koni",
            "Küre",
            "Katı Cisimlerde Yüzey Alanı ve Hacim Hesapları",
        ]), // Geometri: 45 konu

        new(SubjectBranch.Fizik,
        [
            "Vektörler",
            "Bağıl Hareket",
            "Kuvvet, Tork ve Denge",
            "Kütle Merkezi",
            "Basit Makineler",
            "Hareket (Konum, Yer Değiştirme, Sürat ve Hız)",
            "Sabit İvmeli Hareket",
            "Newton'un Hareket Yasaları",
            "Sürtünme Kuvveti",
            "İş, Güç ve Enerji",
            "Enerjinin Korunumu",
            "Atışlar (Serbest Düşme, Düşey Atış, Yatay Atış, Eğik Atış)",
            "İki Boyutta Hareket",
            "İtme ve Momentum",
            "Çarpışmalar",
            "Elektriksel Kuvvet ve Elektrik Alan",
            "Elektriksel Potansiyel ve Potansiyel Enerji",
            "Paralel Levhalar ve Sığa (Kondansatör)",
            "Manyetik Alan ve Manyetik Kuvvet",
            "İndüksiyon",
            "Alternatif Akım",
            "Transformatörler",
            "Düzgün Çembersel Hareket",
            "Dönme, Yuvarlanma ve Açısal Momentum",
            "Kütle Çekim Kuvveti ve Kepler Yasaları",
            "Basit Harmonik Hareket",
            "Dalga Mekaniği",
            "Elektromanyetik Dalgalar",
            "Işığın Girişimi ve Kırınımı",
            "Doppler Olayı",
            "Atom Modelleri",
            "Atom Fiziğine Giriş",
            "Büyük Patlama ve Parçacık Fiziği",
            "Radyoaktivite",
            "Fisyon ve Füzyon",
            "Özel Görelilik",
            "Kara Cisim Işıması",
            "Fotoelektrik Olay",
            "Compton Olayı",
            "De Broglie Dalga Boyu ve Madde Dalgaları",
            "Modern Fiziğin Teknolojideki Uygulamaları",
        ]), // Fizik: 41 konu

        new(SubjectBranch.Kimya,
        [
            "Kimya Bilimi",
            "Atom ve Periyodik Sistem",
            "Kimyasal Türler Arası Etkileşimler",
            "Kimyanın Temel Kanunları",
            "Kimyasal Hesaplamalar",
            "Asitler, Bazlar ve Tuzlar",
            "Maddenin Halleri",
            "Karışımlar",
            "Doğa ve Kimya",
            "Kimya Her Yerde",
            "Modern Atom Teorisi",
            "Atomun Kuantum Modeli ve Kuantum Sayıları",
            "Elektron Dizilimi ve Orbitaller",
            "Periyodik Özelliklerin Değişimi",
            "Kimyasal Bağlarda Molekül Geometrileri ve Hibritleşme",
            "Gazlar",
            "İdeal Gaz Yasaları",
            "Gaz Karışımları ve Kısmi Basınçlar",
            "Gerçek Gazlar",
            "Sıvı Çözeltiler",
            "Çözünürlük ve Çözünürlüğe Etki Eden Faktörler",
            "Derişim Birimleri",
            "Koligatif Özellikler",
            "Kimyasal Tepkimelerde Enerji",
            "Entalpi ve Hess Yasası",
            "Bağ Enerjileri",
            "Kimyasal Tepkimelerde Hız",
            "Tepkime Hızına Etki Eden Faktörler",
            "Kimyasal Tepkimelerde Denge",
            "Denge Sabiti ve Le Chatelier İlkesi",
            "Sulu Çözelti Dengeleri",
            "Asit-Baz Dengesi ve pH Hesaplamaları",
            "Tampon Çözeltiler",
            "Titrasyon",
            "Çözünürlük Dengesi",
            "Kimya ve Elektrik",
            "İndirgenme-Yükseltgenme Tepkimeleri",
            "Elektrokimyasal Hücreler ve Standart Elektrot Potansiyelleri",
            "Elektroliz",
            "Korozyon",
            "Organik Kimyaya Giriş",
            "Karbon Kimyasına Giriş ve Hibritleşme",
            "Organik Bileşiklerde Adlandırma ve İzomerlik",
            "Hidrokarbonlar (Alkanlar, Alkenler, Alkinler, Aromatik Bileşikler)",
            "Alkoller",
            "Eterler",
            "Aldehitler ve Ketonlar",
            "Karboksilik Asitler",
            "Esterler",
            "Aminler ve Amitler",
            "Organik Bileşiklerin Kullanım Alanları",
            "Enerji Kaynakları ve Bilimsel Gelişmeler",
            "Fosil Yakıtlar ve Alternatif Enerji Kaynakları",
            "Sürdürülebilirlik ve Yeşil Kimya",
        ]), // Kimya: 54 konu

        new(SubjectBranch.Biyoloji,
        [
            "İnsan Fizyolojisine Giriş ve Denetleyici-Düzenleyici Sistemler",
            "Sinir Sistemi",
            "Merkezi Sinir Sistemi ve Çevresel Sinir Sistemi",
            "Refleksler",
            "Endokrin Sistem ve Hormonlar",
            "Duyu Organları",
            "Destek ve Hareket Sistemi",
            "Kemikler, Kaslar ve Eklemler",
            "Sindirim Sistemi",
            "Dolaşım Sistemi",
            "Kan ve Kan Dokusu",
            "Lenf Dolaşımı",
            "Bağışıklık Sistemi",
            "Solunum Sistemi",
            "Üriner Sistem (Boşaltım Sistemi)",
            "Üreme Sistemi",
            "İnsanda Embriyonik Gelişim",
            "Komünite Ekolojisi",
            "Komünitede Tür İçi ve Türler Arası İlişkiler",
            "Süksesyon (Ekolojik Değişim)",
            "Popülasyon Ekolojisi",
            "Popülasyon Dinamiği ve Büyüme Eğrileri",
            "Genden Proteine",
            "Nükleik Asitlerin Keşfi ve DNA'nın Yapısı",
            "DNA'nın Kendini Eşlemesi (Replikasyon)",
            "Genetik Şifre ve Protein Sentezi",
            "Transkripsiyon ve Translasyon",
            "Mutasyon ve Modifikasyon",
            "Genetik Mühendisliği ve Biyoteknoloji",
            "Canlılarda Enerji Dönüşümleri",
            "Canlılık ve Enerji (ATP)",
            "Fotosentez",
            "Fotosentez Hızına Etki Eden Faktörler",
            "Kemosentez",
            "Hücresel Solunum",
            "Oksijenli Solunum",
            "Oksijensiz Solunum ve Fermantasyon",
            "Bitki Biyolojisi",
            "Bitkilerin Yapısı (Kök, Gövde, Yaprak)",
            "Bitkisel Dokular",
            "Bitkilerde Madde Taşınması",
            "Bitkilerde Terleme ve Su Alışverişi",
            "Bitkisel Hormonlar ve Hareketler",
            "Bitkilerde Eşeyli Üreme ve Çimlenme",
            "Canlılar ve Çevre",
            "Çevre Sorunları ve Etkileri",
            "Doğal Kaynakların Sürdürülebilirliği",
        ]), // Biyoloji: 47 konu

    ];

    /// <summary>
    /// Ders adı. Tanım Domain'de (<see cref="SubjectBranchNames"/>); burası yalnızca
    /// tohumlayıcının okunaklı kalması için kısayol — iki ayrı ad listesi tutulmuyor.
    /// </summary>
    /// <summary>Sınav seviyesi. Ders adı seviyeye göre değişebilir (bkz. DisplayName).</summary>
    public enum ExamLevel { Tyt, Ayt }

    /// <summary>
    /// Katalogda görünecek DERS adı. Branş adıyla aynı olmak zorunda değildir.
    /// </summary>
    /// <remarks>
    /// TEK İSTİSNA AYT TÜRKÇE → "Edebiyat". ÖSYM'de bu test "Türk Dili ve Edebiyatı"dır ve
    /// konuları (Divan şiiri, Servetifünun, Tanzimat romanı…) TYT Türkçesiyle — dil bilgisi,
    /// paragraf, sözcükte anlam — hiç örtüşmez. İkisine de "Türkçe" demek, portföyünde ders
    /// arayan öğrenciye iki ayrı listeyi aynı adla gösteriyordu.
    ///
    /// BRANŞ YİNE DE <see cref="SubjectBranch.Turkce"/> KALIYOR: rozetler branş üzerinden
    /// hesaplanıyor ve TYT Türkçe ile AYT Edebiyat anlatan biri tek bir "Türkçe Ustası"
    /// olmalı — tıpkı TYT ve AYT matematiğin tek "Matematik" rozetinde toplanması gibi.
    /// Görünen ad ile rozet ekseni ayrı şeyler; burada ayrıldıkları tek nokta bu.
    /// </remarks>
    public static string DisplayName(SubjectBranch branch, ExamLevel level) =>
        branch == SubjectBranch.Turkce && level == ExamLevel.Ayt
            ? "Edebiyat"
            : SubjectBranchNames.Of(branch);
}
